### PR TITLE
Adds LogHandler documentation to README (branch 1.6.0)

### PR DESCRIPTION
**Pull request by abelsromero**
Updates README.

Should also update https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc, or include it?

### CODE REVIEW

**Comment by robertpanzer** [comment]
I think it would make sense to also have it in the integrator guide. 
Can you copy this description into it as well?

**Comment by abelsromero** [comment]
No problem, but I just saw there are 2; one in `/docs`, another in `asciidoctorj-documentation/src/main/asciidoc/`.

**Comment by robertpanzer** [comment]
If you update the source in asciidoctorj-documentation/src/main/asciidoc and run the build the document under /docs should be updated automatically.
The file under docs has the includes resolved, so that it can be viewed directly on Github.

**Comment by abelsromero** [comment]
Done! I also updated the versions of the modules

**Comment by abelsromero** [comment]
I relaunched Travis on my repo and Java 7 and 8 work fine.
Since master already drop java7 (macos will need more work), I can look at it for 1.60 in another branch. wdyt?

**Comment by robertpanzer** [comment]
I triggered a rebuild on Travis and it looks good now as well.
Thank you!!!

**Comment by abelsromero** [comment]
Now that I got your attention :% how about this? https://github.com/asciidoctor/asciidoctorj/pull/675

btw, keeping master and 1.6.0 is a pain...I do appreciate what you have been doing

**Comment by robertpanzer** [comment]
Sorry for being a bit slow atm (and also forgetting things) :-D 
I just triggered a rebuild with Java 8 on Travis, it didn't seem to have any result. After that I'll merge.

Thanks for being patient with me and all your awesome contributions!

**Comment by abelsromero** [comment]
> Thanks for being patient with me

Afaik some got married recently...so I understand

**Comment by mojavelinux** [comment]
> Afaik some got married recently...so I understand

Wait, who got married? Friends want to know these things ;)

**Pull request merged**
