### PR TITLE
Fixes #929. Replace references to Travis by GHActions in README

### LINKED ISSUE #929: CI section in README still points to Travis
See
https://github.com/asciidoctor/asciidoctorj/blob/master/README.adoc#continuous-integration

### PR DESCRIPTION
**Pull request by abelsromero**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [x] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?
Fixes refences to TravisCI in README and removes deprecated badge.

How does it achieve that?
Corrects content of README.

Are there any alternative ways to implement this?
:man_shrugging: 

Are there any implications of this pull request? Anything a user must know?
No

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 
:heavy_check_mark: 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
I noted this reference to Travis vars in the upstream test script. https://github.com/asciidoctor/asciidoctorj/blob/06bf178b58bb8a76fb007def5afe39ec00d0da7a/test-asciidoctor-upstream.sh#L6
Do you want to remote it and clean* all travis references?

* Feel bad after all the good service Travis has provided

**Comment by robertpanzer** [comment]
Awesome, thank you.
I think the conditional exit from test-asciidoctor-upstream.sh can be removed, as we take care of this in the Github action now:
https://github.com/asciidoctor/asciidoctorj/blob/06bf178b58bb8a76fb007def5afe39ec00d0da7a/.github/workflows/continuous-integration.yaml#L41-L45

It would be awesome if you could also remove that part too.

**Comment by abelsromero** [comment]
Done :+1:

**Comment by robertpanzer** [comment]
🚀 Thank you!

**Pull request merged**
