### PR TITLE
Run Wildfly IT with Java16

### LINKED ISSUE #1000: Project does not build with Java 16
Seeing issues here and there I tried to build the project and "no surprise" found it does not build. First step would  be to upgrade gradle to https://docs.gradle.org/7.0-milestone-3/release-notes.html.

After that we may need more changes.

```
~/github/asciidoctorj >>> ./gradlew test                                                                                                                            ±[A4●][master]
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :asciidoctorj-api:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctorj-api:compileJava'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x18434b8) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x18434b8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

```

### PR DESCRIPTION
**Pull request by abelsromero**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [x] Build improvement

## Description

What is the goal of this pull request?
Run `asciidoctorj-wildfly-integration-test` with Java16

How does it achieve that?
The fix only requires upgrading dependencies to latests
```
    arquillianVersion = '1.6.0.Final'
    arquillianWildflyVersion = '3.0.1.Final'
```
And addind the repo `https://maven.repository.redhat.com/ga/`, without it, build fails unable to collect certan specific dependencies.

Are there any alternative ways to implement this?
Tried different version to see if the extra maven repo could be removed without much luck. A part form that, not much alternatives to test.

Are there any implications of this pull request? Anything a user must know?
No

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #1000  

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by robertpanzer** [comment]
Are these new files in the spring boot integration test necessary?
Or would it make sense to ignore them to .gitignore?

**Comment by abelsromero** [comment]
> Are these new files in the spring boot integration test necessary?
> Or would it make sense to ignore them to .gitignore?

Obviously not :roll_eyes:  fixed

**Comment by abelsromero** [comment]
All green and without the `onlyIf`, we are safe then.

**Comment by robertpanzer** [comment]
Awesome! Thank you!🍻🎉🚀

**Pull request merged**
