### PR TITLE
Fixed title

### PR DESCRIPTION
**Pull request by lefou**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks!

**Comment by robertpanzer** [comment]
Thank you @mojavelinux for cherry-picking into asciidoctorj-1.6.0  96b1650b95eea7b
Just wanted to do that myself! :)

**Comment by mojavelinux** [comment]
Sorry about that, I was cleaning up my own mess. I merged not thinking
about the other branches, so wanted to apply before it slipped though the
cracks. I'll remember not to hit the merge button next time without
thinking ;)

**Comment by robertpanzer** [comment]
Everything's fine!
I've seen the PR ad the merge yesterday and I noted to myself that I'll cherry-pick it when I'm back at the keyboard.

**Comment by mojavelinux** [comment]
+1

**Comment by mojavelinux** [comment]
@robertpanzer You can revert my manual merge and cherry pick the original commit so that it's correct in all branches. Just force push to the branches I put it in. If you want me to do it instead, just let me know. Thanks!

**Comment by robertpanzer** [comment]
@mojavelinux Sure, will do it. 
But I'd prefer to do it without force pushing if you meant to really delete your commit.

**Comment by mojavelinux** [comment]
In this case, a force push is fitting...though you can do a reverse commit and then cherry pick too.

**Comment by robertpanzer** [comment]
I'll do the revert and cherry pick tomorrow. 
At least Schalk is actively following the 1.6.0 branch and I don't want to make him stumble over a change in history.

**Comment by mojavelinux** [comment]
Thanks Robert!

**Comment by robertpanzer** [comment]
Reverted and cherry-picked on asciidoctorj-1.5.x and asciidoctorj-1.6.0

**Pull request merged**
