### PR TITLE
Related to #368: added more code highlighting examples for 'rouge'

### PR DESCRIPTION
**Pull request by abelsromero**
Since the forum request was about scala, I have added a scala example alongside with others languages.
Also some are embedded and some are included to make use we don't have an issue with this.

### CODE REVIEW

**Comment by mojavelinux** [comment]
:+1:

**Comment by abelsromero** [comment]
I don't think it made to the release, still, I hope it can be added.

**Comment by mojavelinux** [comment]
Rouge will be included as part of AsciidoctorJ PDF 1.5.0-alpha.9, but Robert hasn't released it yet.

**Comment by robertpanzer** [comment]
Oh, I already released this afternoon :-(

**Comment by robertpanzer** [comment]
Here it is:
http://jcenter.bintray.com/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.9/ <http://jcenter.bintray.com/org/asciidoctor/asciidoctorj-pdf/1.5.0-alpha.9/>

**Comment by mojavelinux** [comment]
Excellent! And I can confirm that rouge is in there, so it should work.

**Comment by abelsromero** [comment]
@robertpanzer let me know to which branch resend, [asciidoctorj-1.6.0](https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0)?

**Comment by robertpanzer** [comment]
I'm pretty sure, we'll see a pdf alpha.10 before 1.6.0.
So this branch already feels right and I can cherry-pick into 1.6.0. 

I just wonder if we could add these great examples to some documentation to increase the visibility?

**Comment by abelsromero** [comment]
> I just wonder if we could add these great examples to some documentation to increase the visibility?

Already added to maven examples.
https://github.com/asciidoctor/asciidoctor-maven-examples/pull/28

**Comment by robertpanzer** [comment]
👍🏻

**Comment by robertpanzer** [comment]
Rebased the upgrade to asciidoctor-pdf 1.5.0.alpha.9 as well as this PR onto asciidoctorj-1.6.0: 9bd0e75

**Pull request merged**
