### PR TITLE
Add Chocolatey packaging.

### PR DESCRIPTION
**Pull request by robertpanzer**
Create a Chocolatey .nuspec based on the Bintray -bin.zip package.

This PR is a cherry-pick from the old master that got lost in the merge from 1.6 into master.

### CODE REVIEW

**Comment by abelsromero** [comment]
I noticed that `chocolatey/tools/chocolateyinstall.ps1` mentions version 1.5.6

**Comment by robertpanzer** [comment]
Oh right, I'll update this to 1.5.7.
I've never used this myself though, I guess @geraldcombs updates the file when publishing the release to chocolatey.

**Comment by mojavelinux** [comment]
If it's going into master, shouldn't it be 1.6.0? Or does the script have to mention the last released version?

**Comment by abelsromero** [comment]
Seeing how the script works and that, according to the comments in it, it requires some file editing + getting an API key, I am pretty sure it's been edited manually and not commited back.

So probably not a big deal, but still It'd be nice to align it with 1.6.0.

**Pull request merged**
