### PR TITLE
Test Plantuml diagram generation

### PR DESCRIPTION
**Pull request by robertpanzer**
This PR is for now just a playground to get PlantUML/graphviz diagram generation tested on our CI systems.

### CODE REVIEW

**Comment by robertpanzer** [comment]
Woot!

Didn't think that it would run that smooth.

PlantUML tests now seem to run fine on Win and Linux.

**Comment by abelsromero** [comment]
> Didn't think that it would run that smooth.

I hope that was more a matter of mistrust in the tools than in your skills :wink:

**Comment by robertpanzer** [comment]
Hehe... Thank you!
Was more wondering if the binaries are available on the PATH and that it is available to the tests.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
