### PR TITLE
Upgrade gradle to 4.4.1 and make compatible with Java9

### PR DESCRIPTION
**Pull request by tisoft**
related to #591

### CODE REVIEW

**Comment by robertpanzer** [comment]
Thanks for helping out on this!
I'll test as soon as I find the time.

**Comment by tisoft** [comment]
Its not finished yet, using the PR so that I can use travis for testing :)

**Comment by tisoft** [comment]
Build is passing now on travis. The failure on AppVeyer seems unrelated to me, could you take a look?

Next step would be to make it actually compile under Java 9

**Comment by tisoft** [comment]
Ready for testing :)

**Comment by robertpanzer** [comment]
Thanks! 
I was about to cherry-pick your commit on the master PR, but this is better. :)

**Pull request merged**
