### PR TITLE
Try lifting to Gradle 7.0

### PR DESCRIPTION
**Pull request by robertpanzer**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [x] Build improvement

## Description

What is the goal of this pull request?

This PR tries to bring the build to Gradle 7.0.
I can't tell if the dependency declarations are all correct, the new scopes are still a mystery right now (I didn't spend much time yet digging into them)
Except the wildfly integration test everything seems to run on OSX.

@abelsromero Could you please check if this works on your machine? I've seen your issue yesterday and made an attempt myself today.

How does it achieve that?

Are there any alternative ways to implement this?

Are there any implications of this pull request? Anything a user must know?

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
Worked fine for me on Linux and MacOS.

**Comment by robertpanzer** [comment]
Thanks! And the CI build also worked with Java 16 now.
I guess we can look at the wildfly test later, that seems to be a Java/Gradle problem rather than an AsciidoctorJ problem.

**Comment by robertpanzer** [comment]
I'll check the poms tomorrow if they are still correct.

**Comment by abelsromero** [comment]
Running locally I see `Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.security.ProtectionDomain[] java.security.AccessControlContext.context accessible: module java.base does not "opens java.security" to unnamed module @18b9aa90`with is to be expected with Java 16. Probably something wildfly team is already aware.

**Comment by robertpanzer** [comment]
I managed to fix the Wildfly integration test. 
Apparently I have been doing not enough JavaEE & Arquillian development lately, stupid me.

Also upgraded Gradle to 7.0-rc-1.

The generated poms are mostly identical now to the previous version, only the dependency for jcommander has changed from compile to runtime. I think this is fine since this library is only used for the CLI.

**Comment by robertpanzer** [comment]
Stupid me, I was running with a wrong Java version, Wildfly still fails on Java 16.
Excluded it for no only for Java 16.

**Comment by abelsromero** [comment]
I got it working on my Linux machine.
Your changes game me the idea the issue may be on Arquillian side, just updated versions and added a RH repo required (don't ask me why)

```
ext {
    arquillianVersion = '1.6.0.Final'
    arquillianWildflyVersion = '3.0.1.Final'

    wildflyVersion = '23.0.0.Final'
}

repositories {
    maven {
        url "https://maven.repository.redhat.com/ga/"
    }
}
```

Furthermore, this runs without adding any extra Java16 condition to the build scripts.

**Comment by robertpanzer** [comment]
Great find!
Do you want to create a PR? Then I'd merge mine now and merge yours on top.

**Pull request merged**
