### PR TITLE
Update tiltGemVersion to 2.0.8

### PR DESCRIPTION
**Pull request by msgilligan**
For Issue #655

### CODE REVIEW

**Comment by robertpanzer** [comment]
Awesome, thank you!
This looks good to me.
@mojavelinux Do you think that upgrade would have any impact? As far as I can tell, Asciidoctor core depends on tilt ~> 2.0.0 anyway and should therefore work with 2.0.8 as well, right?

**Comment by msgilligan** [comment]
Sometimes I contribute to open source projects on byte at a time ;-)

**Comment by robertpanzer** [comment]
If it’s the right byte you’re making OSS better one byte at a time :)

**Comment by mojavelinux** [comment]
Yes, we should upgrade. Thanks for the bytes!

**Comment by robertpanzer** [comment]
Thanks! I'll try to cherry-pick the commit into the 1.6.0 branch.

**Pull request merged**
