### PR TITLE
Remove deprecated from Asciidoctor interface

### LINKED ISSUE #1201: Remove deprecated methods from Asciidoctor interface
Methods already marked should be removed for v3.0.0 release.
Those are:
  * Methods that use `OptionsBuilder` or Map<String,?> for options instead of `Options` instance
  * `readDocumentHeader` methods, that are replaced by `load`

We'll need to document these changes in the migration guide.

### PR DESCRIPTION
**Pull request by abelsromero**
## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [x] New breaking feature
- [x] Documentation update
- [ ] Build improvement

## Description

*What is the goal of this pull request?*

* Remove deprecated methods in `org.asciidoctor.Asciidoctor` interface to streamline API.
Just methods using `org.asciidoctor.Options` remain now.
* Remove `readDocumentHeader` methods and `org.asciidoctor.ast.DocumentHeader` class

**:warning: IMPORTANT: This is a branch from the branch in PR https://github.com/asciidoctor/asciidoctorj/pull/1200, this is to be merged later, I am marking as draft for now as a reminder. No rush, there's plenty of time.**

*How does it achieve that?*

Simply remove the methods and refactor the required code.
Special mention to `WhenDocumentHeaderIsRequired` test, we could remove it, but I just reimplemented with the new API to ensure users can still obtain the same information.

*Are there any alternative ways to implement this?*
No, it's only remove, no changes in the methods lefts.

*Are there any implications of this pull request? Anything a user must know?*

It's breaking for v3.0.0 but we add a migration guide to help.

## Issue

Fixes #1201 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
@mojavelinux I am documenting on the migration guide how to use `parse_header_only` option, but I suspect this is one of those internal things that users should not use? Is that the case?

**Comment by abelsromero** [comment]
Rebased from main, ready for review :tada:

**Review by robertpanzer — APPROVED** [review]
LGTM

**Comment by robertpanzer** [comment]
Thanks!

**Pull request merged**
