### PR TITLE
chore: upgrade to Gradle 5.5.1

### PR DESCRIPTION
**Pull request by Fiouz**
Fixes asciidoctor/asciidoctorj#747

### CODE REVIEW

**Comment by robertpanzer** [comment]
Thanks! I'll test it out as soon as I find the time.

**Comment by Fiouz** [comment]
Forgot to mention the [checksum verification](https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification) for the modified binary:

```shell
$ sha256sum < gradle/wrapper/gradle-wrapper.jar
3dc39ad650d40f6c029bd8ff605c6d95865d657dbfdeacdb079db0ddfffedf9f *-
```

The value must match the _Wrapper JAR Checksum_ at https://gradle.org/release-checksums/#5.5.1

**Comment by robertpanzer** [comment]
I just had a first try.
I got the error below. Do you have an idea what could have gone wrong?
The submodule asciidoctorj-distribution builds an artifact with the same group and artifact id as asciidoctorj-core, only with a different file type. Could this be a problem?
```
:asciidoctorj-distribution:distZip (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.003 secs.
:asciidoctorj-distribution:signArchives (Thread[Execution worker for ':' Thread 2,5,main]) started.

> Task :asciidoctorj-distribution:signArchives FAILED
:asciidoctorj-distribution:signArchives (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.14 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctorj-distribution:signArchives'.
> Duplicate key Signature asciidoctorj:zip.asc:asc:bin

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctorj-distribution:signArchives'.
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Duplicate key Signature asciidoctorj:zip.asc:asc:bin
        at org.gradle.plugins.signing.Sign.getSignaturesByKey(Sign.java:247)
        at org.gradle.plugins.signing.Sign_Decorated.getSignaturesByKey(Unknown Source)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:75)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:341)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:72)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.call(AbstractNestedRuntimeBeanNode.java:119)
        at org.gradle.api.internal.tasks.properties.annotations.NestedBeanAnnotationHandler.visitPropertyValue(NestedBeanAnnotationHandler.java:63)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:55)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:42)
        at org.gradle.api.internal.tasks.properties.DefaultTaskProperties.resolve(DefaultTaskProperties.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:65)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 24 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5.1/userguide/command_line_interface.html#sec:command_line_warnings
```

**Comment by Fiouz** [comment]
With 0ceeb1078f2ee31160556402e855e336e48ec7d1, I can reproduce the issue (after generating dummy a dummy key) with Gradle version **5.1**
```
gradle --no-daemon --stacktrace -i clean :asciidoctorj-distribution:signArchives
```
Gradle **5.0** does not exhibit the issue. I'll see what could be done and will re-open this request when fixed.

**Comment by Fiouz** [comment]
fix(build): remove duplicated Signature from the 'signArchives' task
    
    The extra Signature went unnoticed until Gradle 5.1 improved up-to-date
    checking for the Sign task, and revealed the duplicate; the build breaks
    when checking whether it should skip ':asciidoctorj-distribution:signArchives'

**Comment by robertpanzer** [comment]
First tests looked good, thank you!
Can you please add an entry in the CHANGELOG.adoc? Then I'd like to merge this PR.

**Comment by robertpanzer** [comment]
Awesome! Thank you! 🎉

**Pull request merged**
