### PR TITLE
Fixes #588. Fix rendering to Java streams

### LINKED ISSUE #588: Writing generated doc to an output stream does not work (undefined method `<<')
If I try to write the generated document (in this case with backend PDF) to an output stream I get this exception:

```
Exception in thread "main" org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `<<' for #<Java::JavaIo::ByteArrayOutputStream:0x7378ff35>
	at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:460)
	at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:486)
	at org.asciidoctor.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:481)
	at Test.main(Test.java:82)
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `<<' for #<Java::JavaIo::ByteArrayOutputStream:0x7378ff35>
	at RUBY.render_header(uri:classloader:/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:191)
	at RUBY.render(uri:classloader:/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:164)
	at RUBY.render(uri:classloader:/gems/prawn-2.2.2/lib/prawn/document.rb:378)
	at RUBY.write(uri:classloader:/gems/asciidoctor-pdf-1.5.0.alpha.16/lib/asciidoctor-pdf/converter.rb:2826)
	at RUBY.write(uri:classloader:/gems/asciidoctor-1.5.6.1/lib/asciidoctor/document.rb:1083)
	at RUBY.convert(uri:classloader:/gems/asciidoctor-1.5.6.1/lib/asciidoctor.rb:1507)
	at RUBY.convert(<script>:85)
```

I call asciidoctorj like this:
```
ByteArrayOutputStream baos = new ByteArrayOutputStream();
Asciidoctor.Factory.create().convert(
		out,
		OptionsBuilder.options()
				.backend("pdf")
				.toStream(baos)
				.headerFooter(true)
				.safe(SafeMode.UNSAFE)));
```
The same happens for each other implementation of OutputStream.

Environment:
asciidoctorj 1.6.0 alpha 6
asciidoctorj-pdf 1.5.0 alpha 16
jruby 9.1.13.0

### PR DESCRIPTION
**Pull request by robertpanzer**
This PR tries to fix #588 as well as rendering HTML to OutputStreams.
The key is to wrap the OutputStream into sth that implements methods like `write` (used by Asciidoctor core) and `<<` and `size` (used by pdf-core).

Direct calls of `write` to an OutputStream don't work from Ruby because the method is overloaded and JRuby can't figure out which one to call.

I don't know if I messed up encodings, because I just get RubyStrings in and I simply convert them to bytes without using an encoding. Do I have to pass in an encoding that is available somewhere.

PDF generally works but in comparison to rendering to a File the title page is missing.
@mojavelinux Is there any chance that this is not an error in this PR but the normal behavior of Asciidoctor-PDF under certain circumstances?

### CODE REVIEW

**Comment by robertpanzer** [comment]
Seems like the property `document.notitle` is false when writing to a stream. Trying to find out why.

**Comment by robertpanzer** [comment]
Ah found it.
When writing to a stream the `header_footer` option must be set. Then the title page is also rendered to the stream. Sounds fair.
Will do some more testing with rendering themes etc, but atm it looks like it's good to go. Dittaa diagrams already seemed to work fine.

**Comment by robertpanzer** [comment]
Huh???
The Codenarc plugin failed because it suddenly loads a version of groovy that is only compatible with Java8?
Why??? I didn't change the version of Gradle

**Comment by robertpanzer** [comment]
Seems to work now.
The test renders the same document to a PDF file and stream and checks that they contain the same byte sequence. So I think we're fine no.

Should we also try to fix this on master/1.5.x and possibly release a 1.5.6.1?

**Comment by mojavelinux** [comment]
Is this something we should check for / support in core?

**Pull request merged**
