### PR TITLE
Added support for converters that create arbitrary content that write…

### PR DESCRIPTION
**Pull request by robertpanzer**
… it to the file itself.

This PR is far from finished.
It wants to work on the multitude of requirements for converters that create arbitrary content other than Strings (see #234 and #304).
Having said that this PR doesn't try to go for the requirement for multiple streams.

This commit adds the interface `WritingConverter`.
Letting a `Converter` also implement this interface mimics an Asciidoctor Ruby converter that includes the `Asciidoctor::Writer` module.
That is the converter writes the content itself to the target file.
(Writing to streams is still making my brain hurt at the moment, because the current implementation in AsciidoctorJ for converting to a Writer is outside of Asciidoctor/Ruby, that is the document is converted to a string and that is written to the Writer)

This is also the precondition for allowing a `Converter` to create non-stringy content.
Therefore the `Converter` interface is now a generic interface that has to declare the results it produces.
Such a converter that also wants to support writing its result to files should therefore also be a `WritingConverter` because the converter is the only one who knows how to serialize the result.

The `Asciidoctor` interface is extended with several generic convert & convertFile methods that take an expected result type so that the caller can receive arbitrary object content instead of only strings.
The existing convert methods delegate to these new methods with a expected result type of String.
If the result type does not match the actual result a `ClassCastException` will be thrown.

### CODE REVIEW

**Comment by robertpanzer** [comment]
Btw: I am pretty fine with refusing this PR. 
I just hope that a discussion around this subject brings us closer to a good solution. 
Because atm I have the impression that it's really difficult to find a good solution that satisfies all expectations.

**Comment by robertpanzer** [comment]
Maybe it would also make sense to make a converter that converts to Strings is a specialization of a converter with arbitrary results and provide a default implementation for `write` with String outputs.

**Comment by robertpanzer** [comment]
Just changed the interface `WritingConverter` to receive an `java.io.OutputStream` instead of a `java.io.File`.
The stream is defined via `OptionsBuilder.toStream()`. 
For `OptionsBuilder.toFile()` the `ConverterProxy` opens and closes a `FileOutputStream`.
Thereby it is now possible to create streaming converters in Java.
A wrapping converter for the existing Ruby PDF backend could implement the desired PDF streaming for PDF documents.

For the current Ruby based converters this would certainly not work out of the box.
(But maybe that's even possible with setting the to_file option to sth that implements `:write`.

**Comment by robertpanzer** [comment]
One build failed on Travis because TorqueBox responded with HTTP 500 when trying to fetch the Asciidoctor 1.5.3.dev gem. The other builds succeeded.

**Comment by mojavelinux** [comment]
I'm thrilled that you are starting to tackle this problem. It's a tough challenge, but has a very rewarding result because it frees us from the String-only world.

I'm not sure the WritingConverter is the right name for this type. I recognize that Writer may be too generic, so how about OutputWriter? I say that because these are orthogonal concerns. One converts from AsciiDoc to another object. The other writes that object somewhere. I suppose we could have a base class that mixes the two, but it seems better if we just require that the converter class extend the OutputWriter interface. I could also get behind `OutputFormatWriter`.

**Comment by mojavelinux** [comment]
In general, I think you are well on your way there.

> Thereby it is now possible to create streaming converters in Java.

I like this. Big step forward.

What I can't tell is whether converters can leave off the type and still work with a String result. Is it necessary to specify? If so, we might want to think about having a StringConverter as a base class that fills in this type for convenience. wdyt?

I'm very interested to know what @ysb33r thinks about this new contract. This could really bring the AsciidoctorJ API the next level of maturity.

**Comment by robertpanzer** [comment]
> I'm not sure `WritingConverter` is the right name for this type.

I'm always bad at naming things :)

> I could also get behind `OutputFormatWriter`.

I like that name. At least the `Writer` cannot be completely decoupled from the Converter (Asciidoctor Ruby requires that) so I'd like to keep a link.
So `abstract class AbstractConverter implements Converter, OutputFormatWriter`?

> If so, we might want to think about having a StringConverter as a base class that fills in this type for convenience.

Good idea!
For someone who wants to get into this technology it will be much simpler to start with a `StringConverter`.

> it seems better if we just require that the converter class extend the OutputWriter interface.

Yes! And the abstract `StringConverter` could provide an implementation for `write`.
Thereby we would already get a streaming StringConverter for free.
And the `write` method would not surface before the user wants to go one step further and implement a binary converter.

**Comment by mojavelinux** [comment]
> I'm always bad at naming things :)

It's the hardest thing in programming. A community of minds is the only weapon we have against it :)

**Comment by mojavelinux** [comment]
> abstract class AbstractConverter implements Converter, OutputFormatWriter?

Precisely what I had in mind.

**Comment by mojavelinux** [comment]
> For someone who wants to get into this technology it will be much simpler to start with a StringConverter.

Exactly. This is the first step and likely the tutorial will introduce the first-time converter author in this way.

**Comment by ysb33r** [comment]
> abstract class AbstractConverter implements Converter, OutputFormatWriter?

I like that

**Comment by robertpanzer** [comment]
Renamed `WritingConverter` to `OutputFormatWriter`.
Require every Java based Converter to be an `OutputFormatWriter`.
Introduced `StringConverter` for simple string based converters.

**Comment by ysb33r** [comment]
What is still not clear for me is at what stage the `write` will be called. Is the expectation that asciidoctor core will invoke this after processing the AST?

**Comment by robertpanzer** [comment]
Well, it works fully integrated with Asciidoctor Ruby:

First `convert()` will be called. This returns a result, of type String or anything else.

If the converted result should _not_ be written to a file this result is returned to the caller.

If the converted result should be written to a file and the converter mixed in the `Writer` module the method `write()` is invoked passing in the converted result and the stream.
If the converter does not include the `Writer` module Asciidoctor simply writes the content to the file (No stream!) hoping that Rubys `::File` knows how to handle that.

With this PR every Java based converter includes the `Writer` module!

So actually the purpose of the `Writer` module was never to invoke it from the `convert` method as we had guessed some time before but to be called after conversion by Asciidoctor to write the generated content somewhere.
(That's still sth that has to be mentioned, we write to streams but there is no real streaming where we can read very large documents and write them somewhere while rendering, it's always parse, convert, write.)

When writing to a file Asciidoctor Ruby returns the parsed `Document`, but in AsciidoctorJ we return `null` because we have no union types or sth like that to return alternatives depending on the options.

Did it become clearer now?
We definitely have to explain that very carefully in the manuals.

**Comment by mojavelinux** [comment]
> actually the purpose of the Writer module was never to invoke it from the
> convert method as we had guessed some time before but to be called after
> conversion by Asciidoctor to write the generated content somewhere.
>

Spot on!

**Comment by robertpanzer** [comment]
Fixed an NPE with string converters that return `null` from `convert` like the leanpub converter.
Aligned the README with the changes to the converters.
But I feel we have to go for providing dedicated documentation soon. I could have added much much more to the README which would let it explode.

**Comment by mojavelinux** [comment]
>  I could have added much much more to the README which would let it explode.

It's probably the right time to start working on the layout of the AsciidoctorJ manual. See https://github.com/asciidoctor/asciidoctorj/issues/333.

**Comment by MonaElsa** [comment]
Hi everyone, 
what is the status on this topic. I need a way to convert to a pdf stream.

**Pull request merged**
