### PR TITLE
Add Java17 to gh-actions

### PR DESCRIPTION
**Pull request by abelsromero**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [x] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?

Add support for Java 17.

How does it achieve that?

Adds automated tests and any other build/code related change.

Are there any alternative ways to implement this?

:man_shrugging: we'll see...

Are there any implications of this pull request? Anything a user must know?

Added matrix to Windows build to test Java 11 and 17.

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
Seeing the pipeline I wonder why do we have the special Windows setup?

**Comment by abelsromero** [comment]
There might be some "CI-commit driven development", I'll mark the PR as draft until ready.

**Comment by robertpanzer** [comment]
Do you mean why we build on windows at all or why do we have a custom flow for that?

The custom flow is for ./gradlew vs. gradlew.bat.

**Comment by robertpanzer** [comment]
Thanks for taking this 🙏
I had it on my list for after vacation, so thanks a lot for this PR 🙂🎉🙏

**Comment by abelsromero** [comment]
> why do we have a custom flow for that?
> 
> The custom flow is for ./gradlew vs. gradlew.bat.

For maven we just invoke ".mvnw" and seems to work https://github.com/asciidoctor/asciidoctor-maven-plugin/blob/main/.github/workflows/build.yaml, I can try if we can get rid of the custom tomorrow.

**Pull request merged**
