### PR TITLE
Try to fix running tests in IntelliJ

### PR DESCRIPTION
**Pull request by robertpanzer**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [x] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?

It seems like it is not possible anymore to run or debug a single test in IntelliJ anymore since very recently.
This PR tries to fix this.

How does it achieve that?

My last status was that IntelliJ complained about the annotation org.osgi.annotation.Export not being available.
Changing the dependency type from compileOnly to implementation seems to solve this situation.
(Don't ask me why, I don't understand why compileOnly is not good here either)

@abelsromero As you were also facing this issue, could you please test this?

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by robertpanzer** [comment]
Changing the scope of the dependency makes Gradle add a dependency with runtime scope to the pom.
I am not sure right now if this is acceptable or not, right now we don't have a dependency from asciidoctorj-api to org.osgi:osgi.annotation.

**Comment by robertpanzer** [comment]
It seems like adding a testRuntimeOnly dependency on osgi is sufficient to run tests in IntelliJ.
Plus it does not have the "downside" of adding a dependency to the pom.

**Comment by robertpanzer** [comment]
Merging for now since we don't change the dependencies with it.
If we still feel that we should expose an optional dependency on osgi.annotation we can still add it later.

**Comment by abelsromero** [comment]
Did nothing to me :shrug: more the opposite

image

**Comment by robertpanzer** [comment]
Hmmm.. is it complaining about everything in red?
The last missing piece for me to run a test was the osgi annotations.

**Comment by abelsromero** [comment]
Interesting enough dependencies are ok in the Gradle pannel, but in the code complains it cannot find junit. But in any case I can stll do a "Run all project tests" and debug with that. It's really odd.

**Pull request merged**
