### PR TITLE
Add .travis-upstream-only.yml

### PR DESCRIPTION
**Pull request by robertpanzer**

### CODE REVIEW

**Comment by mojavelinux** [comment]
```yml
install: true
script: bash test-asciidoctor-upstream.sh
```

The `install: true` line disables any action in this step of the build lifecycle.

**Comment by robertpanzer** [comment]
My bad. 
I thought that the file was executed (seems like this is not possible) instead of being read by the rakefile and sent as a delta config. 
Will fix ASAP.

**Comment by robertpanzer** [comment]
Changed the .travis-upstream-only.yml as commented.
That should be it, right?

**Comment by mojavelinux** [comment]
Yep, that should do it. But we'll find out for sure soon enough :)

**Comment by robertpanzer** [comment]
Thanks for reviewing! :)

**Comment by mojavelinux** [comment]
I looks like it worked!

https://travis-ci.org/asciidoctor/asciidoctorj/builds/279391632

:tada:

**Comment by robertpanzer** [comment]
Awesome, will cherry-pick it into the 1.6.0 branch today :+1:

**Pull request merged**
