### PR TITLE
Improve local development docs

### LINKED ISSUE #835: README instructions on publishing to local repo might be a bit off
## Current Behavior
Wanting to test some changes I made to asciidoctorj against another project, I followed instructions in the README to publish to my local maven repo.

I successfully started with [build the project](https://github.com/asciidoctor/asciidoctorj#build-the-project):
>```
>$ git clone https://github.com/asciidoctor/asciidoctorj
>  cd asciidoctorj
>  ./gradlew assemble
>```

Then had a bit of trouble with [publish the artifacts](https://github.com/asciidoctor/asciidoctorj#publish-the-artifacts):

> To build, assemble (but not sign) and install the archives (jars and distribution zip) into the local Maven repository, run:
>```
>$ ./gradlew -PpublishRelease=true install
>```

#### symptom
Here's the output I got:
```
> Configure project :
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-api. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-arquillian-extension. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-test-support. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html

FAILURE: Build failed with an exception.

* Where:
Script '/Users/lee/other-proj/asciidoctorj/gradle/sdkman.gradle' line: 4

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'sdkman_consumer_key' for project ':asciidoctorj-distribution' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
```
#### work-around
I worked around this by appending the following dummy config to my `gradle.properties`
```
sdkman_consumer_key=<some_key>
sdkman_consumer_token=<some_token>
```

#### symptom
After working around problem 1, I retried `./gradlew -PpublishRelease=true install`, this time things looked to good:
```
> Configure project :
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-api. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-arquillian-extension. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-test-support. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
Configuration(s) specified but the install task does not exist in project :asciidoctorj-distribution.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 0s
13 actionable tasks: 13 up-to-date
```
But nothing got installed to my local maven repo.
#### work-around
I'm not familiar with your build so I hacked it by adding `apply plugin: 'maven'` under the `subprojects` config on [this line](https://github.com/asciidoctor/asciidoctorj/blob/d68c825273fd5768ca2f396238f600f117e3763f/build.gradle#L85).

I reran `./gradlew -PpublishRelease=true install` and got the following output:
```

> Configure project :
No Signatory configured for project asciidoctorj. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-api. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-arquillian-extension. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-distribution. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html
No Signatory configured for project asciidoctorj-test-support. Skip signing! See https://docs.gradle.org/current/userguide/signing_plugin.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
38 actionable tasks: 5 executed, 33 up-to-date
```
And the jars (at least the ones I needed) installed to my local maven repo:
```
$ tree ~/.m2/repository/org/asciidoctor                                                                                                                  ✔  11738  14:23:19
/Users/lee/.m2/repository/org/asciidoctor
├── asciidoctorj
│   ├── 2.1.1-SNAPSHOT
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-bin.tar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-bin.zip
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-javadoc.jar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT-sources.jar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT.jar
│   │   ├── asciidoctorj-2.1.1-SNAPSHOT.pom
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
├── asciidoctorj-api
│   ├── 2.1.1-SNAPSHOT
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT-javadoc.jar
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT-sources.jar
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT.jar
│   │   ├── asciidoctorj-api-2.1.1-SNAPSHOT.pom
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
├── asciidoctorj-arquillian-extension
│   ├── 2.1.1-SNAPSHOT
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT-javadoc.jar
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT-sources.jar
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT.jar
│   │   ├── asciidoctorj-arquillian-extension-2.1.1-SNAPSHOT.pom
│   │   └── maven-metadata-local.xml
│   └── maven-metadata-local.xml
└── asciidoctorj-test-support
    ├── 2.1.1-SNAPSHOT
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT-javadoc.jar
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT-sources.jar
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT.jar
    │   ├── asciidoctorj-test-support-2.1.1-SNAPSHOT.pom
    │   └── maven-metadata-local.xml
    └── maven-metadata-local.xml

8 directories, 26 files
```
## Expected Behavior
No mods required to install jars to local maven repo.

## Action
I am probably not the best guy to fix this one, but if I am close to correct with the above, am happy to provide a PR.

### PR DESCRIPTION
**Pull request by abelsromero**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [x] Documentation update
- [x] Build improvement

## Description

What is the goal of this pull request?

Started wanting to close #835, for that renamed guide _Build_ o _Local Development_ and structured a bit to better distinguish the common tasks for development.
But also found the following things while working on it:
* Signature is not enabled by default. So we don't need `skip.signing` for local development. Also `apply plugin: 'signing'` is applied in the main project, so there's no need to apply again in `signing.gradle`. ¿should we remove it in one of the 2 places?
* Added _asciidoctorj-springboot-integration-test_ to layout description.

How does it achieve that?
With much care and appreciation.

Are there any alternative ways to implement this?
no

Are there any implications of this pull request? Anything a user must know?
no

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 
Fixes #835 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by robertpanzer** [comment]
Thanks for updating the docs.
I wonder if we should move any docs about local development exclusively to the README? Anyone who wants to hack on AsciidoctorJ has to pass by the Github repo.

¿should we remove it in one of the 2 places?
Where did you find the other `apply plugin 'signing'`? In the main build.gradle I only see the declaration of that plugin, but not that it's actually applied.

**Comment by abelsromero** [comment]
> I wonder if we should move any docs about local development exclusively to the README? Anyone who wants to hack on AsciidoctorJ has to pass by the Github repo.

Precisely I was going to propose to reduce the README at some point. Handling duplication prone to issues. Furthermore,  the search options in the docs site are awesome, I have come to love it and find it much more productive than single page docs + browser search.

> ¿should we remove it in one of the 2 places?

My imagination, right next to "coding late is not a good thing" 😓

**Comment by robertpanzer** [comment]
> My imagination, right next to "coding late is not a good thing" 😓

No worries! This happens a lot to me all the time recently, even when it's not late.
I am happy we're looking with more eyes recently on these things.

> Precisely I was going to propose to reduce the README at some point. 

What do you think about removing the local development parts from the README then entirely and replacing it with a link to the corresponding page at docs.asciidoctor.org?

**Comment by abelsromero** [comment]
> What do you think about removing the local development parts from the README then entirely and replacing it with a link to the corresponding page at docs.asciidoctor.org?

Seems reasonable, I'll apply the change later.

**Comment by mojavelinux** [comment]
> the search options in the docs site are awesome, I have come to love it and find it much more productive than single page docs + browser search.

@abelsromero You don't know how happy it makes me to read that. It really means a lot to me. Thanks!

**Pull request merged**
