### PR TITLE
Fixes #334. Add support for defining the backend name of a converter …

### LINKED ISSUE #334: Add support for defining backend name for a converter in the converter class itself
Currently the backend name of a converter is only defined when it is registered at the converter registry: `asciidoctor.javaConverterRegistry().register(MyConverter.class, "mybackendname")`

This came up in the discussion in #332:

It should be possible to define at least one backend name in the converter class itself so that the converter can be registered without a backend name: `asciidoctor.javaConverterRegistry().register(MyConverter.class)`

Options are:
- Allow the converter writer to add an annotation to the `Converter` implementation like `@Backend("mybackendname")`
- Add a method `String getBackendName()` to the `Converter` class so that the converter writer is forced to define a backend name. (Even though the abstract base class `AbstractConverter` could return `null`.)

When no default backend name is defined by the converter `register(Class)` could throw an IllegalArgumentException.

### PR DESCRIPTION
**Pull request by robertpanzer**
…via an annotation @Backend.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Annotations FTW!

I want to address one open question before we move forward with this. We inherited the term "backend" from AsciiDoc Python. However, it's not the best term to describe the purpose it serves. The long-term goal in Asciidoctor is to replace the usage of this term with one that is more fitting. Since we're defining a public API here, we should use it as an opportunity to migrate to the newer terminology.

On the Ruby side, I decided to name the DSL method `register_for`. I like this because it leaves the term implicit. Thus, on the Java side we might go with `@RegisterFor`. Another way of writing this is `@Handles` or `@Converts`. If you'd rather keep it as a noun, then I'd suggest `@Name` or `@ConverterName`. I'm open to other ideas.

I'm not sure which of those is the right choice, but for sure we should avoid `@Backend`.

**Comment by mojavelinux** [comment]
I'm liking `@Converts(<name>)`. That reads really nicely.

```java
@Converts("leanpub")
class LeanpubConverter extends AbstractTextConverter {
    ...
}
```

**Comment by robertpanzer** [comment]
What about @ConvertsTo?
I think we cannot get completely get rid of the term backend, as it's used in the options, attributes, etc. 
With the term @ConvertsTo the meaning of backend could be defined more precise as a target format instead of referring to the whole bundle of a of converter and a target. 
With only @Converts I'm somehow missing a preposition.

**Comment by mojavelinux** [comment]
> I think we cannot get completely get rid of the term backend, as it's used in the options, attributes, etc.

We will eventually...and by that I mean have alternative terminology that maps to the same functionality (for backwards compatibility). In most of those places, the word "converter" will fit.

> What about @ConvertsTo? With only @Converts I'm somehow missing a preposition.

Good point. Another option is `@ConverterFor`, but I could get behind `@ConvertsTo` as well.

**Comment by robertpanzer** [comment]
> Good point. Another option is @ConverterFor, but I could get behind @ConvertsTo as well.
> 
@ConverterFor is better. I've not seen verbs in annotation names yet.

**Comment by mojavelinux** [comment]
> In most of those places, the word "converter" will fit.

Correction. I meant to say "format".

**Pull request merged**
