### PR TITLE
Fix code snippit error in Integrator's Guide

### LINKED ISSUE #959: Integrator's Guide Code Snippit Error
While studying the Integrator's Guide, I noticed what I think must be a paste error under the [converter](https://github.com/asciidoctor/asciidoctorj/blob/master/docs/integrator-guide.adoc#publish-everywhere-adapt-asciidoctor-to-your-own-target-format) section.

The source code example reads:

```Java
        File test_adoc = //...

        asciidoctor.javaConverterRegistry().register(TextConverter.class); // <1>

        String result = asciidoctor.convertFile(
                test_adoc,
                OptionsBuilder.options()
                        .backend("text")                                   // <2>
                        .toFile(false));

            File test_adoc = //...

            String result = asciidoctor.convertFile(
                    test_adoc,
                    OptionsBuilder.options()
                            .backend("text")                                   // <1>
                            .toFile(false));

```

But I think should read:

```Java
        File test_adoc = //...

        asciidoctor.javaConverterRegistry().register(TextConverter.class); // <1>

        String result = asciidoctor.convertFile(
                test_adoc,
                OptionsBuilder.options()
                        .backend("text")                                   // <2>
                        .toFile(false));
```

I will follow up with a PR.

### PR DESCRIPTION
**Pull request by lread**
## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [x] Documentation update
- [ ] Build improvement

## Description

Fix a paste error.

## Issue

Fixes #959

## Release notes

I'm guessing this is not necessary for such a small doc fix.

### CODE REVIEW

**Comment by robertpanzer** [comment]
Hi Lee!

Thank you for your PR!

One thing that is not obvious in our build is that the documentation under docs/ is built from asciidoctorj-documentation.
So it would be cool if you could fix the issue under asciidoctorj-documentation and then run `./gradlew asciidoctorj-documentation:build` to have both generation source and target in sync.

**Comment by lread** [comment]
I think failed build is due to junit.org being momentarily down: 
https://twitter.com/junitteam/status/1315685977269112832

**Comment by lread** [comment]
Yup, junit.org is now back up and the build passed.

I expect a squash is in order after review, lemme know.

**Comment by abelsromero** [comment]
> Yup, junit.org is now back up and the build passed.

```
javadoc: error - Error fetching URL: http://junit.org/javadoc/latest/
```
Open question because this got me by surprise and I am intrigued. Is there any reason why junit pulls remote data during build?

**Comment by lread** [comment]
> Open question because this got me by surprise and I am intrigued. Is there any reason why junit pulls remote data during build?

I think it is actually javadoc doing the pulling, here's some [details](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDEDJFI).

**Comment by robertpanzer** [comment]
Hi Lee,

just want to check if you forgot to commit your changes to asciidoctorj-documentation/src/main/asciidoc/integrator-guide.adoc?
Otherwise the next build will also override your updates to docs/integrator-guide.adoc.

**Comment by lread** [comment]
Thanks for checking @robertpanzer. 

The problem turned out to be in the included Java source code rather than in adoc itself.  
Here's the relevant commit where I removed duplicated  `//tag::include[]`s and `//end::include[]`s from Java source a7db084c41164092182504b79e34f38db97cdc5b

**Comment by lread** [comment]
One extra note @robertpanzer, `./gradlew asciidoctorj-documentation:build` did not update adocs for me when only the Java source code changed.  I forced the update by manually clearing out `./docs/*`.

**Comment by robertpanzer** [comment]
Thank you!

**Pull request merged**
