### PR TITLE
Several doc fixes (remove bintray references, replace discuss by Zulip, ...)

### PR DESCRIPTION
**Pull request by abelsromero**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [x] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?

Started only wanting to remove Bintray references but added other fixes found.
  * Remove bintray references
  * Replace discuss by Zulip
  * Remove unused attributes in README
  * Update jruby-version to 9.2.17.0 (in docs)

How does it achieve that?

Applies small fixes in the docs and comments.

Are there any alternative ways to implement this?
No.

Are there any implications of this pull request? Anything a user must know?
No.

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
@robertpanzer btw, do chocolately package need to be updated like the ones in sdkman?

**Comment by robertpanzer** [comment]
I don't actually know a lot (=nothing) about chocolatey. 
I would assume that this has the same problem. 
Until now the publications to chocolatey were always done by @geraldcombs, so he might know.

**Comment by geraldcombs** [comment]
The download URL is set in the Chocolatey packaging in chocolatey/tools/chocolateyinstall.ps1. I switched the URL from bintray to https://search.maven.org/remotecontent?filepath=org/asciidoctor/asciidoctorj/VERSION/asciidoctorj-VERSION-bin.zip in 3a843aa. If there's a more preferred URL it should be easy enough to change.

**Comment by abelsromero** [comment]
@geraldcombs my question is about past packages, they won't be available if I understand correctly.

**Comment by geraldcombs** [comment]
> @geraldcombs my question is about past packages, they won't be available if I understand correctly.

It looks like you would have to create "fix versions" of each package: https://docs.chocolatey.org/en-us/create/create-packages#package-fix-version-notation.

**Comment by robertpanzer** [comment]
Thank you, Abel!

**Pull request merged**
