### PR TITLE
resolves #1050 fix upstream build to build against the specified ref

### LINKED ISSUE #1050: Upstream build is using github.event.client_payload.branch incorrectly
The configuration for the upstream build is using the value of github.event.client_payload.branch to look for a reference in its own repository. This is incorrect. It should clone the branch for which the CI job was triggered (which is the default behavior of the checkout action). Then, it should use the value of github.event.client_payload.branch in ./test-asciidoctor-upstream.sh to get the right branch of Asciidoctor core to build against.

### PR DESCRIPTION
**Pull request by mojavelinux**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [x] Build improvement

## Description

What is the goal of this pull request? To fix the build against upstream.

How does it achieve that? It uses the branch specified in the payload in the correct place.

Are there any alternative ways to implement this? No.

Are there any implications of this pull request? Anything a user must know? It will fix the build in Asciidoctor core.

## Issue

Fixes #1050

### CODE REVIEW

**Comment by mojavelinux** [comment]
@robertpanzer Could I proceed with merging so I can test this? I'm pretty sure it is correct, but it's hard to know for sure until it is run in situ.

**Comment by robertpanzer** [comment]
Sure, feel free to merge in this repo whenever you need it. I'll go ahead and merge.

**Comment by mojavelinux** [comment]
Perfect. Thanks @robertpanzer!

**Comment by mojavelinux** [comment]
Yeah, it worked!

**Pull request merged**
