### PR TITLE
#284 Don't fail for files in root directory with absolute path

### PR DESCRIPTION
**Pull request by robertpanzer**
Fix for #284 

@lordofthejars If you accept this PR I would cherry-pick the commit into the master branch.

### CODE REVIEW

**Comment by robertpanzer** [comment]
Will check for the test error on windows next week when I have a windows box again at reach

**Comment by abelsromero** [comment]
I cannot send a PR right now, but I tested this on my machine and I'd like to add what I found.

I think the problem is in how Linux absolute paths are cheched in (our friend) Windows here:
https://github.com/robertpanzer/asciidoctorj/blob/d7ce297cab1f2101e4a1216434b3c5d4351ce386/asciidoctorj-core/src/main/java/org/asciidoctor/GlobDirectoryWalker.java#L79
Since `File.separator` returns `\` in Windows (L75), and the path does start with a letter, the path in the test `/this_file_does_not_exist.adoc` is not recognized as an absolute path, and that's why it fails. 
Also, I fear this way to check for paths does not fix all possible options in Windows. That's because java.io.File accepts unix paths also on windows, when something like '/folder/another_folder/file.adoc' is passed, it is translated to 'c:\folder\another_folder\file.adoc'. Basically it gets the default unit letter from windows registry and changes the slashes.

In order to better test this I've been thinking that maybe it makes sense to move `isAbsoluteGlobExpression` into `org.asciidoctor.internal.IOUtils` and call it something like 'isAbsolutePath'. That way we can write tests to validate all possible options and decouple `GlobDirectoryWalker` class from specifc OS treatments (in that case findIndexOfUnglobbedPart
and isWindows should be moved too).

wdyt?

**Comment by robertpanzer** [comment]
:+1: from my side

I am a little embarrassed that I forgot about the edge case of a file in the root. 
I think your proposal is a really good idea!

**Comment by robertpanzer** [comment]
@abelsromero I think I got it right now and it is even simpler than I thought.

Travis failed on one test because the TCP connection was reset while fetching dependencies, so I suppose that everything is working fine now.

@abelsromero @lordofthejars Are you both ok with the way it is resolved now?

**Pull request merged**
