### PR TITLE
resolves #483 fix test against upstream

### LINKED ISSUE #483: configure travis to run only the check task for PR's
Currently every PR seems to fail on travis. In reality the check task is successful. But the `bash test-asciidoctor-upstream.sh` tasks fails.

See https://travis-ci.org/asciidoctor/asciidoctorj/jobs/144690217

Is it necessary to run the bash script for a pull request?

### PR DESCRIPTION
**Pull request by mojavelinux**
* update script to handle new gemspec contents
* only run upstream test on first job in build

### CODE REVIEW

**Comment by mojavelinux** [comment]
This pull request solves some errors, but reveals others. It will also need to be applied against the 1.6.0 branch.

**Comment by robertpanzer** [comment]
Strange thing is that the upstream build worked for me locally also before this PR. 
Great that the travis is green again finally!

**Comment by robertpanzer** [comment]
Cherry-picked into asciidoctorj-1.6.0 as f27691fe8c9537cf88a802c0a38166f2e624e394

**Comment by mojavelinux** [comment]
Almost green ;)

I want to clarify that this was an issue related specifically to JRuby 1.7, which doesn't implement a method option I was using the the gemspec. However, I applied a fix that will work for all Rubies, so it should be very safe now. :+1:

**Comment by mojavelinux** [comment]
It appears we get a test failure on AsciidoctorJ on AppVeyor. We should enable the flag that reports the test failures on the commandline so we can see them. The other option is to define the test reports as artifacts, which AppVeyor makes available in the workspace after the build.

For example:

```
artifacts:
  - path: **/build/reports/tests/**
```

**Comment by robertpanzer** [comment]
It seems to fail here: https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-distribution/src/test/groovy/org/asciidoctor/diagram/WhenDitaaDiagramIsRendered.groovy#L84

Seems like the first test or the when has failed so that `png` is not initialized. Wonder why Spock doesn't report that.
Could be this one: https://github.com/jruby/jruby/issues/3957
This test was specifically made to catch such errors :-)

**Comment by mojavelinux** [comment]
> This test was specifically made to catch such errors :-)

At least we can take comfort in the fact that its a meaningful failure ;)

**Pull request merged**
