### PR TITLE
Fix invalid http://asciidoctor.org references

### LINKED ISSUE #1195: Invalid 'http://asciidoctor.org' references
In docs, Javadocs, etc. there are several references to `http://asciidoctor.org` (around 30).

We should:
- [ ] Use only `https` references
- [ ] Update when necessary to point to the new docs site (https://docs.asciidoctor.org/)

For both:
- [ ] v3.0.0
- [ ] v2.5.9

### PR DESCRIPTION
**Pull request by abelsromero**
## Kind of change

- [ ] Bug fix
- [x] New non-breaking feature
- [ ] New breaking feature
- [x] Documentation update
- [ ] Build improvement

## Description

*What is the goal of this pull request?*

Fix invalid http://asciidoctor.org references found in docs and JavaDocs.

*How does it achieve that?*

* Applied https where applicable
* Updated JavaDoc references to current links in https://docs.asciidoctor.org/

*Are there any alternative ways to implement this?*

No.

Are there any implications of this pull request? Anything a user must know?

No.

## Issue

Fixes #1195 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
kudos @mojavelinux almost all of the old links redirect to the newer equivalent so the changes were trivial :tada:

**Comment by mojavelinux** [comment]
That's great to hear! I'd be happy to add any redirects that are missing. Just let me know.

**Comment by abelsromero** [comment]
> That's great to hear! I'd be happy to add any redirects that are missing. Just let me know.

I wouldn't bother, and I went for an as-is update in the PR.
No one else complained about missing redirects, the new site docs.asciidoctor.org is awesome and has been available for years already, and above all, google redirects any "asciidoctor" search to it.

**Comment by robertpanzer** [comment]
Thank you so much for this! 🙌

**Pull request merged**
