### PR TITLE
Simplify Options and Attributes creation

### PR DESCRIPTION
**Pull request by abelsromero**
Make compatible changes to guide users for future changes

Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [ ] New non-breaking feature
- [x] New breaking feature
- [ ] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?

Make the experience interacting with Asciidoctor API simpler and less confusing, while mantaining compatibility with current methods and types.

How does it achieve that?
Marks non-prefered methods as deprecated, so users can strt applying changes.

Are there any alternative ways to implement this?
In terms of making the changes smooth no.

Are there any implications of this pull request? Anything a user must know?
No

## Issue

If this PR fixes an open issue, please add a line of the form:

Related to #977  but does not close it completely.

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by abelsromero** [comment]
I must say, IMHO, that with this changes the interaction is much nicer to the point that I think most new users should be able to do a test without checking the docs.

**Comment by abelsromero** [comment]
Don't merge yet, updating docs.

**Comment by abelsromero** [comment]
This reduces the number of convert methods from 21 to 7 :smile:

**Comment by abelsromero** [comment]
I saw for load we only accept Maps https://github.com/asciidoctor/asciidoctorj/blob/6523da86a6d92a8107c9182bdd3236c1b17b2c47/asciidoctorj-api/src/main/java/org/asciidoctor/Asciidoctor.java#L520-L536. I preffer to deal with that in a separate PR after this since it will require some real code and more tests.

**Comment by robertpanzer** [comment]
Thank you for this, this is great!
I'd like to make a new release soon including this.
Imo these changes justify a new minor release, i.e. 2.5.0.
What do you think?

**Comment by robertpanzer** [comment]
> I preffer to deal with that in a separate PR after this since it will require some real code and more tests.

...and add a PR that makes Asciidoctor.load() accept an instance of `Options`.

**Comment by abelsromero** [comment]
> ...and add a PR that makes Asciidoctor.load() accept an instance of `Options`.

Exactly 😄 just let me add that later today and we should be good to go!

**Pull request merged**
