### PR TITLE
add everything to use asciidoctor-diagram as asciidoctorj-diagram

### PR DESCRIPTION
**Pull request by madmas**
done at Hackergarten Basel January 2015 by @maximmo and @madmas

### CODE REVIEW

**Comment by abelsromero** [comment]
I guess this is related to #265 and means that https://github.com/asciidoctor/asciidoctor-maven-examples will have to be updated soon :+1:

**Comment by madmas** [comment]
@abelsromero thanks for linking the right issue and for the hint - we adpoted it and created a PR :)

**Comment by abelsromero** [comment]
@lordofthejars will it be possible for you to publish a preview version in bintray? That way I can merge the maven examples with litle effort. Otherwise I'll have to set a comment about requiring to work with a local version, you know, download ... sources and install :cry:

**Comment by abelsromero** [comment]
Any chance of getting that preview? If it's not possible I'll keep the PR https://github.com/asciidoctor/asciidoctor-maven-examples/pull/12 in wait

**Comment by mojavelinux** [comment]
Nice!

For future work, I'd like to find a way to reuse the ClasspathHelper stuff in the test suite. I didn't know how to do that in Gradle, so for now I just copied the files...but now we have 3 copies of the file and it's time to think about keeping it DRY.

**Comment by imsandli** [comment]
Hi, I've tried to use asciidoctorj-diagram-1.3.0.preview.1 in combination with the maven-site-plugin but it doesn't recognize it. Using it like in the hackergarten example works fine.

This is how my maven config looks like:
```xml
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-site-plugin</artifactId>
      <version>3.4</version>
      <dependencies>
        <dependency>
          <groupId>org.asciidoctor</groupId>
          <artifactId>asciidoctor-maven-plugin</artifactId>
          <version>1.5.2</version>
        </dependency>
        <dependency>
          <groupId>org.asciidoctor</groupId>
          <artifactId>asciidoctorj-diagram</artifactId>
          <version>1.3.0.preview.1</version>
       </dependency>
      </dependencies>
      <configuration>
        <sourceDirectory>src/docs/asciidoc</sourceDirectory>
        <requires>
          <require>asciidoctor-diagram</require>
        </requires>
      </configuration>
    </plugin>
  </plugins>
</build>
```

The problem is probably that the configuration should be at asciidoctor-maven-plugin. but maven doesn't allow this. Any hints?

**Pull request merged**
