### PR TITLE
Upgrade gradle to 4.4.1

### PR DESCRIPTION
**Pull request by tisoft**
related to #591

### CODE REVIEW

**Comment by tisoft** [comment]
This is for the master branch. In #611 its done for 1.6 with additional changes for Java9 compatibility.

**Comment by robertpanzer** [comment]
Thanks for this great contribution!
I'll take a look at this over the weekend.
I want to test the full flow with making releases etc.

**Comment by robertpanzer** [comment]
It looks like signing of the distribution fails for me, because it tries to sign a .jar instead of the .zip:
```
> Task :asciidoctorj-distribution:distZip 
Putting task artifact state for task ':asciidoctorj-distribution:distZip' into context took 0.0 secs.
Up-to-date check for task ':asciidoctorj-distribution:distZip' took 0.001 secs. It is not up-to-date because:
  Output property 'archivePath' file /Users/robertpanzer/dev/asciidoctorj/asciidoctorj-distribution/build/distributions/asciidoctorj-1.5.7-bin.zip has been removed.

:asciidoctorj-distribution:distZip (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 2.168 secs.
:asciidoctorj-distribution:signArchives (Thread[Task worker for ':' Thread 3,5,main]) started.

> Task :asciidoctorj-distribution:signArchives FAILED
Putting task artifact state for task ':asciidoctorj-distribution:signArchives' into context took 0.0 secs.
Up-to-date check for task ':asciidoctorj-distribution:signArchives' took 0.122 secs. It is not up-to-date because:
  Task has failed previously.

:asciidoctorj-distribution:signArchives (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 0.482 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':asciidoctorj-distribution:signArchives'.
> java.io.FileNotFoundException: /Users/robertpanzer/dev/asciidoctorj/asciidoctorj-distribution/build/libs/asciidoctorj-1.5.7-bin.jar (No such file or directory)
```

Do you have an idea how this could be resolved?

**Comment by mojavelinux** [comment]
I remember having a lot of trouble getting the signing plugin to do the right thing. It seems to be very fragile.

**Comment by tisoft** [comment]
I thing I fixed it. At least locally I can get signed packages now. It feels quite hacky though. I wonder what causes the jar to be part of the artifacts in the first place...

**Comment by robertpanzer** [comment]
Looks good! Thank you so much for this contribution!

**Comment by tisoft** [comment]
I have also updated #611 for the 1.6.0 branch with the same fix.

**Pull request merged**
