### PR TITLE
 Replace JUnit4 by JUnit5

### LINKED ISSUE #1186: Migrate to JUnit5
Trying to bump JUnit to v4 to JUnimake use of newer features I am finding road-blockers.

Normal JUnit4 and some Spock tests can make use of the [vintage compatibility library](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-running), but those with Spock and Arquillian can't.
I see Arquillians hasn't made a proper release in a long time, and the latest Spock integration (`arquillian-spock-core`) is `1.0.0.CR1` from Sept 2019, and is not compatible with newer Spock versions.

Is there any reason no to start rewriting tests to remove Arquillian dependency? I am thinking of re-writing the features as a JUnit5 extension that should work.

I am planning to do this in 2 PRs:
* [x] Set Junit5 as default engine
* [ ] ~Reimplement Arquillian features (Asciidoctor and ClasspathResource injection) as Junit 5 (anything else?), and rewrite tests~ We could keep at the end, see https://github.com/asciidoctor/asciidoctorj/pull/1192

### PR DESCRIPTION
**Pull request by abelsromero**
## Kind of change

- [ ] Bug fix
- [x] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [ ] Build improvement

## Description

*What is the goal of this pull request?*

Complete #1186. JUnit5 is the default now (only used in 'asciidoctorj-wildfly-integration-test' because of Arquillian).
And we have a new JUnit5 tools.
The Arquillian extension is left untouched.

*How does it achieve that?*

 Replace Junit4 by Junit5
    
    * Implement new Junit5 extensions:
       @AsciidoctorInstance & @ClasspathResource annotations
       available to inject Asciidoctor instances and resources into tests.
    * Update all modules to use JUnit5 and the new extensions
      'asciidoctorj-wildfly-integration-test' remains on JUnit4 for
      Arquillian compatibility.
    Other changes:
    * Remove some uses of deprecated APIs
    * Fix typo in sample doc
    * Replace use of IOUtils.readFull(File) by Files.readString(Path)
      where possible to remove third-party dependencies.

*Are there any alternative ways to implement this?*

Not on the base implementation, but the naming of the JUnit5 extensions annotations is open for debate :sweat_smile: (naming is hard).

Are there any implications of this pull request? Anything a user must know?

No.

## Issue

This completely closes the issue :tada: 

Fixes #1186

## Release notes

*Please add a corresponding entry to the file CHANGELOG.adoc*

Already added.

### CODE REVIEW

**Comment by abelsromero** [comment]
I just realized we publish the `asciidoctorj-test-support` artifact.
Right now I have a JUnit5 extension that offers:
* `@ClassResource` will inject a shared Asciidoctor instance into a test field.
* `@TestMethodResource` will inject an new Asciidoctor for each test method.
* `@ClasspathResource("test.txt")` will inject a file from classpath. Can be used as filed or test parameters.

With that, we cover our needs, but maybe the `ClassResource` and `TestMethodResource` nomenclature is not very clear for users. Any suggestion, I was thinking calling it `@AsciidoctorInstance` with a property that accepts an enum to be shared or not :thinking:

**Comment by abelsromero** [comment]
Made some more progress :tada: the arquillian extension is not used but we can keep it, and only the wildfly-integration-test module uses junit 4 now.

I am also thinking renaming `asciidoctorj-test-support` to `asciidoctorj-junit-extenasion`, that would make it's intent clear, and that way it can awaken interest from users.

**Comment by abelsromero** [comment]
Ready :tada:

**Comment by robertpanzer** [comment]
Thank you for this! This is awesome! 🙌

**Pull request merged**
