### PR TITLE
Upgrade Asciidoctor to 2.0.11

### PR DESCRIPTION
**Pull request by robertpanzer**
Thank you for opening a pull request and contributing to AsciidoctorJ!

Please take a bit of time giving some details about your pull request:

## Kind of change

- [ ] Bug fix
- [x] New non-breaking feature
- [ ] New breaking feature
- [ ] Documentation update
- [ ] Build improvement

## Description

What is the goal of this pull request?

Upgrade dependencies to Asciidoctor 2.0.11, rouge and CodeRay.

How does it achieve that?

Are there any alternative ways to implement this?

Are there any implications of this pull request? Anything a user must know?

## Issue

If this PR fixes an open issue, please add a line of the form:

Fixes #Issue 

## Release notes

Please add a corresponding entry to the file CHANGELOG.adoc

### CODE REVIEW

**Comment by mojavelinux** [comment]
I discovered two regressions, so I recommend waiting for 2.0.12, which I'll push out at the end of this week.

**Comment by robertpanzer** [comment]
Awesome, thanks for letting me know! 👍 

Just wondering if the change in the order of calls to the syntax highlighter is intended? (see changes to docs/integrator-guide.adoc which are generated)

**Comment by mojavelinux** [comment]
> Just wondering if the change in the order of calls to the syntax highlighter is intended

Yes, that was fixing a previous regression introduced in Asciidoctor 2 (in other words, we are switching back to the 1.5.x behavior). See https://github.com/asciidoctor/asciidoctor/issues/3786

**Comment by mojavelinux** [comment]
2.0.12 is now available!

**Comment by robertpanzer** [comment]
Just saw your tweet :) Will update this PR asap.

**Pull request merged**
